services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
